# Generated by Django 4.0.4 on 2022-05-05 23:28

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grades',
            name='admin_id',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.SET_DEFAULT, related_name='grades_faculty', to=settings.AUTH_USER_MODEL, verbose_name='Faculty ID'),
        ),
        migrations.AlterField(
            model_name='grades',
            name='final_grade',
            field=models.DecimalField(decimal_places=2, max_digits=3, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)]),
        ),
        migrations.AlterField(
            model_name='subject',
            name='units',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='subject',
            name='year_level',
            field=models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)]),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='age',
            field=models.PositiveIntegerField(),
        ),
    ]
