# Generated by Django 4.0.4 on 2022-08-29 14:46

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('course_id', models.CharField(max_length=20, primary_key=True, serialize=False, verbose_name='Course ID')),
                ('course_name', models.CharField(max_length=50, verbose_name='Course')),
            ],
        ),
        migrations.RenameField(
            model_name='department',
            old_name='description',
            new_name='dep_name',
        ),
        migrations.RemoveField(
            model_name='subject',
            name='year_level',
        ),
        migrations.AddField(
            model_name='grades',
            name='avg_grade',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=3, validators=[django.core.validators.MinValueValidator(1.0), django.core.validators.MaxValueValidator(5.0)]),
        ),
        migrations.AddField(
            model_name='grades',
            name='midterm_grade',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=3, validators=[django.core.validators.MinValueValidator(1.0), django.core.validators.MaxValueValidator(5.0)]),
        ),
        migrations.AlterField(
            model_name='grades',
            name='final_grade',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=3, validators=[django.core.validators.MinValueValidator(1.0), django.core.validators.MaxValueValidator(5.0)]),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='sex',
            field=models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('U', 'Prefer not to say')], max_length=1),
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('stud_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL, verbose_name='Student ID')),
                ('year_level', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(8)], verbose_name='Year Level')),
                ('section', models.CharField(default='UNENROLLED', max_length=10, verbose_name='Section')),
                ('course_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.course', verbose_name='Course')),
                ('dep_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.department', verbose_name='Department')),
            ],
        ),
    ]
